<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\EasyHMSAPI.Domain\EasyHMSAPI.Domain.csproj" />
    <ProjectReference Include="..\EasyHMSAPI.Data\EasyHMSAPI.Data.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="4.0.25.3" />
    <PackageReference Include="MailKit" Version="4.14.1" />
    <PackageReference Include="MediatR" Version="13.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1" />
    <PackageReference Include="Microsoft.OpenApi" Version="1.4.3" />
    <PackageReference Include="MimeKit" Version="4.15.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
    <PackageReference Include="Twilio" Version="7.13.5" />
  </ItemGroup>
</Project>
